"use client"
import './globals.css'
import { useState} from 'react'
import { Inter } from 'next/font/google'
import {AppContext,CartProvider} from '@/components/Context/AppContext'
import { AuthProvider } from './Providers'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'OrderKaro',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <CartProvider>
      <body className={inter.className}>
      <AuthProvider >
      {children}  
      </AuthProvider>
      </body>
    </CartProvider>
    </html>
  )
}
